version: '3'

services:

  tester:
    build: .
    image: nekroze/containaruba:latest
    volumes:
      - ./features:/usr/src/app/features
      - ./test_results:/output
    user: "${UID:-1000}:${GID:-1000}"
